//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

public class MyUtils{
			
	public static System.Random rnd = new System.Random();

	public MyUtils (){


	}


	/* the Fisher-Yates shuffle modern algorithm IN PLACE */
	public static void FisherYatesShuffle(int [] array){
		int N = array.Length;
		for (int i=N-1;i>0 ; i--) {
			int e1 = rnd.Next(0,i+1);		
			int temp = array[i];
			array[i] = array[e1];
			array[e1] = temp;
		}
	}

	public static bool near(Vector3 first,Vector3 other,float distanceParameter){
		if ((other-first).magnitude < distanceParameter) return true;
		return false;
	}
	
}



