//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class TabuSearch	{
				
	Chromosome bestSoFar;

	public TabuSearch (){
	


	
	}

	public void createPopulation(){


	}

	
	/*
	public SOLUTION tabuSearch(){




		s ← s0                                                   
		sBest ← s                                            
		tabuList ← null                                      
		while (not stoppingCondition())           
					5:      candidateList ← null                          
						6:      for(sCandidate in sNeighborhood)
							7:           if(not containsTabuElements(sCandidate, tabuList))
								8:                 candidateList ← candidateList + sCandidate
									9:           end
									10:     end
									11:     sCandidate ← LocateBestCandidate(candidateList)
									12:     if(fitness(sCandidate) > fitness(sBest))
										13:          tabuList ← featureDifferences(sCandidate, sBest)
											14:          sBest ← sCandidate
											15:          while(size(tabuList) > maxTabuListSize)
												16:               ExpireFeatures(tabuList)
													17:          end
													18:     end
													19:  end
													20:  return(sBest)

	}



*/

}

